### ISSUE TITLE
Submit Challenge failed: JWS has an invalid anti-replay nonce:

### ISSUE THREAD

**Issue by vankampenp** [xyanide/CertifyTheWeb-TransIP-DNS-update#1]
Using the CertifyTheWeb-TransIP-DNS-update tool the _acme-challenge txt entry is correctly created. After the waiting period of 300 s, I get the invalid anti-replay nonce error.

Not sure it has to do with this tool though, but any help is appreciated.

Pieter

**Comment by xyanide** [comment]
This doesn't seem related to the DNS update tool unfortunately. Your problem probably lies in an incorrect ip configuration or with an issue within your network or your ISP.

See for more help this issue: https://github.com/lukas2511/dehydrated/issues/547#issuecomment-384729256. Try some of the solutions offered over there.

You could also try to decrease the waiting period and see if that helps?

**Comment by hadifarnoud** [comment]
I checked with multiple ISPs and always get this error# INFO: Using main config file /Users/hadifarnoud/Kamva/code/dehydrated/config
 + CloudFlare hook executing: startup_hook
Processing pooldarshim.ir with alternative names: www.pooldarshim.ir
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Oct  8 14:59:11 2019 GMT (Less than 30 days). Renewing!
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
  + ERROR: An error occurred while sending post-request to https://acme-v02.api.letsencrypt.org/acme/new-order (Status 400)

Details:
HTTP/2 400
server: nginx
date: Thu, 26 Sep 2019 10:08:23 GMT
content-type: application/problem+json
content-length: 112
boulder-requester: 10958181
cache-control: public, max-age=0, no-cache
link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
replay-nonce: 0002w39eyy4VEEi357pBWki1d_camVJ1dDE2OskkJ_HKbpU

{
  "type": "urn:ietf:params:acme:error:badNonce",
  "detail": "JWS has no anti-replay nonce",
  "status": 400
}

**Comment by xyanide** [comment]
@hadifarnoud, if the dns entry is created correctly with the help of the tool, i'm afraid there's nothing I can do to help. Try the https://community.letsencrypt.org/ for help on this particular issue.

Closing this as the error is not related to the TransIP tool.
